### PR TITLE
fix: Build failure due to a dependency error with connectivity_plus.

### LINKED ISSUE #50: Build failure due to a dependency error with connectivity_plus
When building patapata, the following error occurs:

<details>

<summary>error</summary>

```
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../patapata_core/lib/src/network.dart:150:17:
Error: The type 'ConnectivityResult' is not exhaustively matched by the switch cases since it doesn't match 'ConnectivityResult.satellite'.
 - 'ConnectivityResult' is from 'package:connectivity_plus_platform_interface/src/enums.dart' ('../../../../../.pub-cache/hosted/pub.dev/connectivity_plus_platform_interface-2.1.0/lib/src/enums.dart').
        switch (tEvent) {
                ^
Error: Compilation failed.
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:153:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:379:19)
<asynchronous suspension>
#2      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:207:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:895:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:546:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:833:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:546:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:833:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:653:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:94:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:296:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1559:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:487:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:422:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:104:11)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:103:3)
<asynchronous suspension>
```

</details>

This error is caused by an update to `connectivity_plus_platform_interface` , which is a dependency of `connectivity_plus` , that introduced new enum values.

### PR DESCRIPTION
**Pull request by matsuyani556**
# Issue Number
fixes https://github.com/gree/patapata/issues/50

# Summary
- Added NetworkConnectivity.satellite to align with the enum added in connectivity_plus_platform_interface.
- Added a fallback to treat unexpected ConnectivityResult values as NetworkConnectivity.other.

### CODE REVIEW

File: packages/patapata_core/lib/src/network.dart [hunk 1]
```diff
@@ -155,6 +166,9 @@ class NetworkPlugin extends Plugin with WidgetsBindingObserver {
           ConnectivityResult.ethernet => NetworkConnectivity.ethernet,
           ConnectivityResult.bluetooth => NetworkConnectivity.bluetooth,
           ConnectivityResult.vpn => NetworkConnectivity.vpn,
+          ConnectivityResult.satellite => NetworkConnectivity.satellite,
+          // ignore: unreachable_switch_case
+          _ => NetworkConnectivity.other, // coverage:ignore-line
```
Comment (matsuyani556) [inline packages/patapata_core/lib/src/network.dart:171]: I used `NetworkConnectivity.other` instead of `NetworkConnectivity.unknown` because `unknown` is the value right after `NetworkPlugin` is initialized, before the actual `ConnectivityResult` is retrieved.

**Review by Moncader — APPROVED** [review]

**Review by toshiaki-satsuma — APPROVED** [review]
