### PR TITLE
Fix/privacy manifest

### LINKED ISSUE #5: Add iOS privacy manifest
## Description
- According to an announcement from Apple, new rules will be introduced for apps distributed on the App Store that collect data or use specific APIs to explain their purpose to users.
- This needs to be addressed by May 1, 2024, and if not complied with by the deadline, it may be rejected in the store review.

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

### PR DESCRIPTION
**Pull request by toshiaki-satsuma**
# Issue Number
fixes #5 

# Summary
- Update the versions of some libraries to those that are compliant with the Privacy Manifest.
- Update the versions of some libraries.
- Update the minimum supported Flutter version to 3.19.0.
- Modify the test code.

### CODE REVIEW

**Comment by toshiaki-satsuma** [comment]
I am currently fixing the issue with the failing Github Actions checks.

**Comment by toshiaki-satsuma** [comment]
I have completed the revisions, so please feel free to review the PR.

File: packages/patapata_core/lib/src/network.dart [hunk 1]
```diff
@@ -50,32 +50,34 @@ enum NetworkConnectivity {
...
       );
 
   @override
   operator ==(Object other) =>
-      other is NetworkInformation && connectivity == other.connectivity;
+      other is NetworkInformation && connectivities == other.connectivities;
 
   @override
-  int get hashCode => Object.hash('NetworkInformation', connectivity);
+  int get hashCode => Object.hash('NetworkInformation', connectivities);
```
Comment (Moncader) [inline packages/patapata_core/lib/src/network.dart:80]: This is incorrect. This will always be false since you're now comparing two Lists. Before it was checking a single object.

You'll have do a deep compare on the list to see if they are the same or not.

File: packages/patapata_core/lib/src/analytics.dart [hunk 2]
```diff
@@ -486,14 +486,11 @@ class AnalyticsContextProvider extends SingleChildStatelessWidget {
   /// Provide an [analyticsContext] and pass the widget to be wrapped as [child].
   /// Optionally, use the [reset] flag to specify whether to reset the [analyticsContext].
   const AnalyticsContextProvider({
-    Key? key,
+    super.key,
     required this.analyticsContext,
-    required Widget child,
+    required Widget super.child,
```
Comment (Moncader) [inline packages/patapata_core/lib/src/analytics.dart:491]: This comment is for the entire PR. But when you use `super` you don't need to declare the type, just like the `key` above.

File: packages/patapata_core/lib/src/network.dart [hunk 3]
```diff
@@ -146,23 +149,26 @@ class NetworkPlugin extends Plugin with WidgetsBindingObserver {
...
+          ConnectivityResult.other => NetworkConnectivity.other,
+          ConnectivityResult.mobile => NetworkConnectivity.mobile,
+          ConnectivityResult.wifi => NetworkConnectivity.wifi,
+          ConnectivityResult.ethernet => NetworkConnectivity.ethernet,
+          ConnectivityResult.bluetooth => NetworkConnectivity.bluetooth,
+          ConnectivityResult.vpn => NetworkConnectivity.vpn,
+        }
+    ];
+
+    if (_currentNetworkInformation.connectivities == tConnectivity) {
```
Comment (Moncader) [inline packages/patapata_core/lib/src/network.dart:166]: This also is incorrect as this is a list and will always be false.

**Review by Moncader — CHANGES_REQUESTED** [review]

**Review by Moncader — APPROVED** [review]

**Review by Moncader — APPROVED** [review]

**Review by matsuyani556 — APPROVED** [review]
